---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
  - name: Infrastructure/localhost
    type: overthere.LocalHost
    os: UNIX
    children:
      - name: localhost-tf-client
        type: terraform.TerraformClient
        path: !value terraformPath
        workingDirectory: !value workingDir
        cpCommand: !value copyCommand
