kind: Rules
metadata:
  namespace: aws.cloudformation
spec:
  - name: "Change SSH allowed IP addresses definition"
    condition:
      deployedType: aws.cloudformation.DeployedTemplate
    processor:
      - type: freemarker
        description: "Add SSHLocation definition"
        phase: GENERATE
        merge:
          path: "$.Parameters"
          type: jsonpath
        parameters:
          template: "{\
              \"SSHLocation\": {\
            \"Description\": \"The IP address range that can be used to SSH to the EC2 instances\",\
            \"Type\": \"String\",\
            \"MinLength\": \"9\",\
            \"MaxLength\": \"18\",\
            \"Default\": \"0.0.0.0/0\",\
            \"AllowedPattern\": \"(\\\\d{1,3})\\\\.(\\\\d{1,3})\\\\.(\\\\d{1,3})\\\\.(\\\\d{1,3})/(\\\\d{1,2})\",\
            \"ConstraintDescription\": \"must be a valid IP CIDR range of the form x.x.x.x/x.\"\
          }\
          }"
      - type: patch
        description: "Override CidrIp to use SSHLocation reference"
        phase: PATCH
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/Resources/InstanceSecurityGroup/Properties/SecurityGroupIngress/0/CidrIp"
              value: "{\
                        \"Ref\": \"SSHLocation\"\
                      }"
