kind: Macros
metadata:
  namespace: k8s
spec:
  - name: "CpuMemoryLimitsMacro"
    description: "CPU and Memory Limits for the deployment"
    parameters:
      cpuNumber: 2
      memorySize: "2048Mi"
    processor:
      - type: freemarker
        description: "CPU and Memory Limits for the deployment"
        merge:
          path: "$.spec.template.spec.containers[0]"
          type: jsonpath
        parameters:
          templateFile: templates/cpu-mem-limit.ftl

