apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
      nodePort: 30001
